//------------------------------------------------------------------------------
// This file is automatically generated. Do not edit this file                  
//                                                                              
// project:       slon5_test                                                    
// package:       slon5_generated_pkg                                           
//                                                                              
// description:   slon5 alg                                                   
//------------------------------------------------------------------------------

`ifndef MD5_GENERATED_SVH
`define MD5_GENERATED_SVH

//******************************************************************************
//******************************************************************************

`include "slon5.svh"

package slon5_generated_pkg;

    //--------------------------------------------------------------------------
    import slon5_pkg::*;

    //--------------------------------------------------------------------------
    typedef bit unsigned [WORD_WIDTH-1:0] KTable_t[0:STAGE_NUM-1];

    //--------------------------------------------------------------------------
    localparam KTable_t KTable = '{
                                    'hd76aa478, 'he8c7b756, 'h242070db, 'hc1bdceee,
                                    'hf57c0faf, 'h4787c62a, 'ha8304613, 'hfd469501,
                                    'h698098d8, 'h8b44f7af, 'hffff5bb1, 'h895cd7be,
                                    'h6b901122, 'hfd987193, 'ha679438e, 'h49b40821,
                                    'hf61e2562, 'hc040b340, 'h265e5a51, 'he9b6c7aa,
                                    'hd62f105d, 'h02441453, 'hd8a1e681, 'he7d3fbc8,
                                    'h21e1cde6, 'hc33707d6, 'hf4d50d87, 'h455a14ed,
                                    'ha9e3e905, 'hfcefa3f8, 'h676f02d9, 'h8d2a4c8a,
                                    'hfffa3942, 'h8771f681, 'h6d9d6122, 'hfde5380c,
                                    'ha4beea44, 'h4bdecfa9, 'hf6bb4b60, 'hbebfbc70,
                                    'h289b7ec6, 'heaa127fa, 'hd4ef3085, 'h04881d05,
                                    'hd9d4d039, 'he6db99e5, 'h1fa27cf8, 'hc4ac5665,
                                    'hf4292244, 'h432aff97, 'hab9423a7, 'hfc93a039,
                                    'h655b59c3, 'h8f0ccc92, 'hffeff47d, 'h85845dd1,
                                    'h6fa87e4f, 'hfe2ce6e0, 'ha3014314, 'h4e0811a1,
                                    'hf7537e82, 'hbd3af235, 'h2ad7d2bb, 'heb86d391
                                  };

    //--------------------------------------------------------------------------
    typedef bit unsigned [IDX_WIDTH-1:0] GTable_t[0:STAGE_NUM-1];


    //--------------------------------------------------------------------------
    localparam GTable_t GTable = '{
                                     0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
                                     1,  6, 11,  0,  5, 10, 15,  4,  9, 14,  3,  8, 13,  2,  7, 12,
                                     5,  8, 11, 14,  1,  4,  7, 10, 13,  0,  3,  6,  9, 12, 15,  2,
                                     0,  7, 14,  5, 12,  3, 10,  1,  8, 15,  6, 13,  4, 11,  2,  9
                                  };

endpackage : slon5_generated_pkg

`endif //MD5_GENERATED_SVH
